In [43]:
import pandas as pd
from sqlalchemy import create_engine
pd.options.display.float_format = '{:.2f}'.format

In [44]:
population_file = "Resources/Population.csv"
population_data_df = pd.read_csv(population_file)
population_data_df.head()

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62
0,NaN,NaN,NaN,NaN,nan,nan,nan,nan,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
1,Last Updated Date,3/21/2019,NaN,NaN,nan,nan,nan,nan,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
2,NaN,NaN,NaN,NaN,nan,nan,nan,nan,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
3,Country Name,Country Code,Indicator Name,Indicator Code,1960.00,1961.00,1962.00,1963.00,1964.00,1965.00,...,2009.00,2010.00,2011.00,2012.00,2013.00,2014.00,2015.00,2016.00,2017.00,2018.00
4,Aruba,ABW,"Population, total",SP.POP.TOTL,54211.00,55438.00,56225.00,56695.00,57032.00,57360.00,...,101453.00,101669.00,102053.00,102577.00,103187.00,103795.00,104341.00,104822.00,105264.00,nan

In [45]:
population_data_df.dropna()

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62
3,Country Name,Country Code,Indicator Name,Indicator Code,1960.00,1961.00,1962.00,1963.00,1964.00,1965.00,...,2009.00,2010.00,2011.00,2012.00,2013.00,2014.00,2015.00,2016.00,2017.00,2018.00

In [ ]:
new_population_data_df.drop([0, 1, 2], inplace=True)

In [46]:
print(population_data_df[['Data Source', 'Unnamed: 60']])

                                           Data Source   Unnamed: 60
0                                                  NaN           nan
1                                    Last Updated Date           nan
2                                                  NaN           nan
3                                         Country Name       2016.00
4                                                Aruba     104822.00
5                                          Afghanistan   34656032.00
6                                               Angola   28813463.00
7                                              Albania    2876101.00
8                                              Andorra      77281.00
9                                           Arab World  406452690.00
10                                United Arab Emirates    9269612.00
11                                           Argentina   43847430.00
12                                             Armenia    2924816.00
13                                      American Samoa      55599.00
14                                 Antigua and Barbuda     100963.00
15                                           Australia   24210809.00
16                                             Austria    8736668.00
17                                          Azerbaijan    9757812.00
18                                             Burundi   10524117.00
19                                             Belgium   11331422.00
20                                               Benin   10872298.00
21                                        Burkina Faso   18646433.00
22                                          Bangladesh  162951560.00
23                                            Bulgaria    7127822.00
24                                             Bahrain    1425171.00
25                                        Bahamas, The     391232.00
26                              Bosnia and Herzegovina    3516816.00
27                                             Belarus    9501534.00
28                                              Belize     366954.00
29                                             Bermuda      65341.00
..                                                 ...           ...
238  Latin America & the Caribbean (IDA & IBRD coun...  621534921.00
239                                        Timor-Leste    1268671.00
240  Middle East & North Africa (IDA & IBRD countries)  369167489.00
241                                              Tonga     107122.00
242                            South Asia (IDA & IBRD) 1766393714.00
243          Sub-Saharan Africa (IDA & IBRD countries) 1033212743.00
244                                Trinidad and Tobago    1364962.00
245                                            Tunisia   11403248.00
246                                             Turkey   79512426.00
247                                             Tuvalu      11097.00
248                                           Tanzania   55572201.00
249                                             Uganda   41487965.00
250                                            Ukraine   45004645.00
251                                Upper middle income 2556921923.00
252                                            Uruguay    3444006.00
253                                      United States  323405935.00
254                                         Uzbekistan   31847900.00
255                     St. Vincent and the Grenadines     109643.00
256                                      Venezuela, RB   31568179.00
257                             British Virgin Islands      30661.00
258                              Virgin Islands (U.S.)     107510.00
259                                            Vietnam   94569072.00
260                                            Vanuatu     270402.00
261                                              World 7444157356.00
262                                              Samoa     195125.00
263                                             Kosovo    1816200.00
264                                        Yemen, Rep.   27584213.00
265                                       South Africa   56015473.00
266                                             Zambia   16591390.00
267                                           Zimbabwe   16150362.00

[268 rows x 2 columns]

In [65]:
new_population_data_df = population_data_df[['Data Source', 'Unnamed: 60']].copy()
new_population_data_df.head()

         Data Source  Unnamed: 60
0                NaN          nan
1  Last Updated Date          nan
2                NaN          nan
3       Country Name      2016.00
4              Aruba    104822.00

In [66]:
new_population_data_df.drop([0, 1, 2], inplace=True)

In [49]:
population_connection = "root:root@127.0.0.1/population_data_df"
engine = create_engine(f'mysql://{population_connection}')

In [50]:
engine.table_names()

OperationalError: (MySQLdb._exceptions.OperationalError) (1049, "Unknown database 'population_data_df'")
(Background on this error at: http://sqlalche.me/e/e3q8)